     name: Sync with upstream

     on:
       push:
         branches:
           - main

     jobs:
       sync:
         runs-on: ubuntu-latest

         steps:
           - name: Checkout code
             uses: actions/checkout@v2

           - name: Sync with upstream
             run: |
               git remote add upstream https://github.com/coolsnowwolf/lede git fetch upstream
               git merge upstream/main
               git push origin main
